---
all:
  children:
    hypervisors:
      hosts:
        iots:
          ansible_host: iots.i.nokiy.net
          ansible_user: iots

    talos_cluster:
      vars:
        ansible_connection: local
      hosts:
        talos-cp-1:
          talos_role: controlplane
          talos_ip: 192.168.122.11
          talos_mac: "52:54:00:10:00:11"
        talos-worker-1:
          talos_role: worker
          talos_ip: 192.168.122.12
          talos_mac: "52:54:00:10:00:12"
