---
all:
  children:
    hypervisors:
      hosts:
        iots:
          ansible_host: iots.i.nokiy.net
          ansible_user: iots

    k8s_cluster:
      vars:
        ansible_user: ansible
        ansible_ssh_private_key_file: ~/.ssh/scnet
        ansible_ssh_common_args: >-
          -F /dev/null
          -o UserKnownHostsFile=/home/lean/i/home/ansible/known_hosts
          -o StrictHostKeyChecking=accept-new
          -o ProxyCommand="ssh -F /dev/null -o UserKnownHostsFile=/home/lean/i/home/ansible/known_hosts -W %h:%p iots@iots.i.nokiy.net"
      children:
        masters:
          hosts:
            rke2-server-1:
              ansible_host: 192.168.122.11
              vm_mac: "52:54:00:10:00:11"
        workers:
          hosts:
            rke2-agent-1:
              ansible_host: 192.168.122.12
              vm_mac: "52:54:00:10:00:12"
